-- The built-in exercise library (user_id null): every lift Fatty ships with,
-- as it is in production. Presets and templates find exercises by name, so a
-- fresh database only needs the same names. Safe to re-run: skips any name
-- that's already there (the dumbbell migration seeds a few of these too).
--
-- `supabase db reset` runs this after the migrations. To refresh it from a
-- live project:
--   select string_agg(format('  (%L,%L,%L,%L,%L,%L)', name, primary_muscle,
--     secondary_muscles::text, mechanic, equipment, default_rep_range),
--     E',\n' order by primary_muscle, name)
--   from exercise where user_id is null;
insert into public.exercise (user_id, name, primary_muscle, secondary_muscles, mechanic, equipment, default_rep_range)
select null, v.name, v.primary_muscle::public.muscle_group, v.secondary_muscles::public.muscle_group[], v.mechanic, v.equipment, v.rep
from (values
  ('Barbell Bench Press','chest','{front_delt,triceps}','compound','barbell','5-8'),
  ('Cable Fly','chest','{front_delt}','isolation','cable','12-15'),
  ('Chest Dip','chest','{triceps,front_delt}','compound','bodyweight','6-12'),
  ('Decline Barbell Press','chest','{triceps,front_delt}','compound','barbell','6-10'),
  ('Decline Dumbbell Press','chest','{triceps,front_delt}','compound','dumbbell','8-12'),
  ('Dumbbell Bench Press','chest','{front_delt,triceps}','compound','dumbbell','8-12'),
  ('Dumbbell Floor Press','chest','{triceps}','compound','dumbbell','8-12'),
  ('Dumbbell Fly','chest','{front_delt}','isolation','dumbbell','10-15'),
  ('Incline Barbell Press','chest','{front_delt,triceps}','compound','barbell','6-10'),
  ('Incline Cable Fly','chest','{front_delt}','isolation','cable','12-15'),
  ('Incline Dumbbell Press','chest','{front_delt,triceps}','compound','dumbbell','8-12'),
  ('Machine Chest Press','chest','{front_delt,triceps}','compound','machine','8-12'),
  ('Pec Deck','chest','{}','isolation','machine','12-15'),
  ('Push-Up','chest','{triceps,front_delt}','compound','bodyweight','10-20'),
  ('Smith Machine Bench Press','chest','{triceps,front_delt}','compound','machine','6-10'),
  ('Weighted Dip','chest','{triceps,front_delt}','compound','bodyweight','8-12'),
  ('Barbell Row','back','{rear_delt,biceps}','compound','barbell','6-10'),
  ('Chest-Supported Row','back','{rear_delt,biceps}','compound','machine','8-12'),
  ('Chin-Up','back','{biceps}','compound','bodyweight','6-12'),
  ('Deadlift','back','{hamstrings,glutes,traps}','compound','barbell','3-5'),
  ('Dumbbell Bent-Over Row','back','{rear_delt,biceps}','compound','dumbbell','8-12'),
  ('Dumbbell Pullover','back','{chest,triceps}','isolation','dumbbell','10-15'),
  ('Inverted Row','back','{biceps,rear_delt}','compound','bodyweight','8-15'),
  ('Lat Pulldown','back','{biceps,rear_delt}','compound','cable','8-12'),
  ('Lat Pullover','back','{triceps}','isolation','cable','12-15'),
  ('Machine Row','back','{biceps}','compound','machine','8-12'),
  ('Meadows Row','back','{biceps,rear_delt}','compound','barbell','8-12'),
  ('Pendlay Row','back','{rear_delt,biceps,traps}','compound','barbell','5-8'),
  ('Pull-Up','back','{biceps,rear_delt}','compound','bodyweight','5-10'),
  ('Rack Pull','back','{traps,hamstrings}','compound','barbell','4-8'),
  ('Renegade Row','back','{abs,rear_delt}','compound','dumbbell','8-12'),
  ('Seated Cable Row','back','{rear_delt,biceps}','compound','cable','8-12'),
  ('Single-Arm Dumbbell Row','back','{biceps}','compound','dumbbell','8-12'),
  ('Straight-Arm Pulldown','back','{}','isolation','cable','12-15'),
  ('T-Bar Row','back','{biceps,rear_delt}','compound','barbell','8-12'),
  ('Weighted Pull-Up','back','{biceps,rear_delt}','compound','bodyweight','5-8'),
  ('Wide-Grip Lat Pulldown','back','{biceps}','compound','cable','8-12'),
  ('Cable Lateral Raise','side_delt','{}','isolation','cable','12-20'),
  ('Cable Upright Row','side_delt','{traps,biceps}','compound','cable','10-15'),
  ('Dumbbell Lateral Raise','side_delt','{}','isolation','dumbbell','12-20'),
  ('Dumbbell Upright Row','side_delt','{traps}','compound','dumbbell','10-15'),
  ('Leaning Cable Lateral Raise','side_delt','{}','isolation','cable','12-20'),
  ('Machine Lateral Raise','side_delt','{}','isolation','machine','12-20'),
  ('Plate Lateral Raise','side_delt','{}','isolation','other','12-20'),
  ('Upright Row','side_delt','{traps,biceps}','compound','barbell','8-12'),
  ('Cable Rear Delt Fly','rear_delt','{}','isolation','cable','12-20'),
  ('Face Pull','rear_delt','{traps}','isolation','cable','15-20'),
  ('Prone Rear Delt Raise','rear_delt','{}','isolation','dumbbell','12-20'),
  ('Rear Delt Fly','rear_delt','{}','isolation','dumbbell','12-20'),
  ('Reverse Pec Deck','rear_delt','{}','isolation','machine','12-20'),
  ('Arnold Press','front_delt','{side_delt,rear_delt}','compound','dumbbell','8-12'),
  ('Cable Front Raise','front_delt','{}','isolation','cable','12-15'),
  ('Dumbbell Front Raise','front_delt','{}','isolation','dumbbell','10-15'),
  ('Landmine Press','front_delt','{chest,triceps}','compound','barbell','8-12'),
  ('Machine Shoulder Press','front_delt','{triceps,side_delt}','compound','machine','8-12'),
  ('Overhead Press','front_delt','{side_delt,triceps}','compound','barbell','5-8'),
  ('Plate Front Raise','front_delt','{}','isolation','other','12-15'),
  ('Push Press','front_delt','{triceps,traps}','compound','barbell','4-8'),
  ('Seated Dumbbell Shoulder Press','front_delt','{side_delt,triceps}','compound','dumbbell','8-12'),
  ('Standing Military Press','front_delt','{side_delt,triceps}','compound','barbell','5-8'),
  ('Barbell Curl','biceps','{forearms}','isolation','barbell','8-12'),
  ('Cable Curl','biceps','{}','isolation','cable','10-15'),
  ('Cable Rope Hammer Curl','biceps','{forearms}','isolation','cable','10-15'),
  ('Concentration Curl','biceps','{}','isolation','dumbbell','10-15'),
  ('Dumbbell Curl','biceps','{forearms}','isolation','dumbbell','8-12'),
  ('EZ-Bar Curl','biceps','{forearms}','isolation','barbell','8-12'),
  ('Hammer Curl','biceps','{forearms}','isolation','dumbbell','8-12'),
  ('Incline Dumbbell Curl','biceps','{}','isolation','dumbbell','8-12'),
  ('Lean-Forward Cable Curl','biceps','{}','isolation','cable','10-15'),
  ('Machine Preacher Curl','biceps','{}','isolation','machine','10-15'),
  ('Preacher Curl','biceps','{}','isolation','machine','8-12'),
  ('Spider Curl','biceps','{}','isolation','dumbbell','10-15'),
  ('Zottman Curl','biceps','{forearms}','isolation','dumbbell','10-12'),
  ('Bench Dip','triceps','{chest}','compound','bodyweight','10-20'),
  ('Cable Kickback','triceps','{}','isolation','cable','12-15'),
  ('Close-Grip Bench Press','triceps','{chest,front_delt}','compound','barbell','6-10'),
  ('Diamond Push-Up','triceps','{chest}','compound','bodyweight','10-20'),
  ('JM Press','triceps','{chest}','compound','barbell','6-10'),
  ('Overhead Cable Extension','triceps','{}','isolation','cable','10-15'),
  ('Overhead Dumbbell Extension','triceps','{}','isolation','dumbbell','10-15'),
  ('Rope Pushdown','triceps','{}','isolation','cable','10-15'),
  ('Single-Arm Overhead Extension','triceps','{}','isolation','dumbbell','10-15'),
  ('Skull Crusher','triceps','{}','isolation','barbell','8-12'),
  ('Triceps Kickback','triceps','{}','isolation','dumbbell','12-15'),
  ('Triceps Pushdown','triceps','{}','isolation','cable','10-15'),
  ('Barbell Back Squat','quads','{glutes,hamstrings}','compound','barbell','5-8'),
  ('Bulgarian Split Squat','quads','{glutes,hamstrings}','compound','dumbbell','8-12'),
  ('Dumbbell Forward Lunge','quads','{glutes,hamstrings}','compound','dumbbell','8-12'),
  ('Dumbbell Step-Up','quads','{glutes,hamstrings}','compound','dumbbell','8-12'),
  ('Front Squat','quads','{glutes,abs}','compound','barbell','5-8'),
  ('Goblet Squat','quads','{glutes,hamstrings}','compound','dumbbell','10-15'),
  ('Hack Squat','quads','{glutes}','compound','machine','8-12'),
  ('Hip Adduction','quads','{}','isolation','machine','15-20'),
  ('Lateral Lunge','quads','{glutes,hamstrings}','compound','dumbbell','10-15'),
  ('Leg Extension','quads','{}','isolation','machine','12-15'),
  ('Leg Press','quads','{glutes,hamstrings}','compound','machine','8-12'),
  ('Reverse Lunge','quads','{glutes}','compound','dumbbell','8-12'),
  ('Sissy Squat','quads','{}','isolation','bodyweight','10-20'),
  ('Smith Machine Squat','quads','{glutes}','compound','machine','8-12'),
  ('Sumo Squat','quads','{glutes,hamstrings}','compound','dumbbell','10-15'),
  ('Walking Lunge','quads','{glutes,hamstrings}','compound','dumbbell','10-16'),
  ('Dumbbell Romanian Deadlift','hamstrings','{glutes,back}','compound','dumbbell','8-12'),
  ('Glute-Ham Raise','hamstrings','{glutes}','compound','bodyweight','6-12'),
  ('Good Morning','hamstrings','{glutes,back}','compound','barbell','8-12'),
  ('Lying Leg Curl','hamstrings','{}','isolation','machine','10-15'),
  ('Nordic Hamstring Curl','hamstrings','{glutes,calves}','compound','bodyweight','5-10'),
  ('Romanian Deadlift','hamstrings','{glutes,back}','compound','barbell','6-10'),
  ('Seated Leg Curl','hamstrings','{}','isolation','machine','10-15'),
  ('Single-Leg Romanian Deadlift','hamstrings','{glutes}','compound','dumbbell','8-12'),
  ('Cable Glute Kickback','glutes','{hamstrings}','isolation','cable','12-20'),
  ('Cable Pull-Through','glutes','{hamstrings}','compound','cable','10-15'),
  ('Curtsy Lunge','glutes','{quads,hamstrings}','compound','dumbbell','10-12'),
  ('Donkey Kick','glutes','{hamstrings}','isolation','dumbbell','12-20'),
  ('Fire Hydrant','glutes','{}','isolation','dumbbell','12-20'),
  ('Frog Pump','glutes','{}','isolation','bodyweight','15-25'),
  ('Glute Bridge','glutes','{hamstrings}','compound','dumbbell','12-20'),
  ('Hip Abduction','glutes','{}','isolation','machine','15-20'),
  ('Hip Thrust','glutes','{hamstrings}','compound','barbell','8-12'),
  ('Reverse Hyperextension','glutes','{hamstrings}','isolation','machine','12-20'),
  ('Single-Leg Hip Thrust','glutes','{hamstrings}','compound','bodyweight','8-15'),
  ('Sumo Deadlift','glutes','{hamstrings,quads,back}','compound','dumbbell','8-12'),
  ('Trap Bar Deadlift','glutes','{quads,hamstrings,back,traps}','compound','barbell','3-6'),
  ('Donkey Calf Raise','calves','{}','isolation','machine','12-20'),
  ('Leg Press Calf Raise','calves','{}','isolation','machine','12-20'),
  ('Seated Calf Raise','calves','{}','isolation','machine','12-20'),
  ('Single-Leg Calf Raise','calves','{}','isolation','bodyweight','12-20'),
  ('Standing Calf Raise','calves','{}','isolation','machine','12-20'),
  ('Ab Wheel Rollout','abs','{}','compound','other','8-15'),
  ('Bicycle Crunch','abs','{}','isolation','bodyweight','15-25'),
  ('Cable Crunch','abs','{}','isolation','cable','12-20'),
  ('Cable Woodchopper','abs','{}','isolation','cable','12-15'),
  ('Decline Sit-Up','abs','{}','isolation','bodyweight','12-20'),
  ('Hanging Knee Raise','abs','{forearms}','isolation','bodyweight','10-15'),
  ('Hanging Leg Raise','abs','{}','isolation','bodyweight','12-20'),
  ('Plank','abs','{}','isolation','bodyweight',NULL),
  ('Russian Twist','abs','{}','isolation','dumbbell','12-20'),
  ('Sit-Up','abs','{}','isolation','bodyweight','15-25'),
  ('Toes-to-Bar','abs','{forearms}','compound','bodyweight','8-15'),
  ('V-Up','abs','{}','isolation','bodyweight','12-20'),
  ('Weighted Crunch','abs','{}','isolation','dumbbell','12-20'),
  ('Farmer''s Carry','forearms','{traps}','compound','dumbbell','carry'),
  ('Reverse Curl','forearms','{biceps}','isolation','barbell','10-15'),
  ('Reverse Wrist Curl','forearms','{}','isolation','dumbbell','12-20'),
  ('Wrist Curl','forearms','{}','isolation','dumbbell','15-20'),
  ('Wrist Roller','forearms','{}','isolation','other','2-4'),
  ('Barbell Shrug','traps','{}','isolation','barbell','10-15'),
  ('Cable Shrug','traps','{}','isolation','cable','12-20'),
  ('Dumbbell Shrug','traps','{}','isolation','dumbbell','10-15'),
  ('Trap Bar Shrug','traps','{}','isolation','barbell','10-15')
) as v(name, primary_muscle, secondary_muscles, mechanic, equipment, rep)
where not exists (
  select 1 from public.exercise e where e.user_id is null and lower(e.name) = lower(v.name)
);
