import type { Metadata, Viewport } from "next";
import { Archivo } from "next/font/google";
import "./globals.css";
import { PwaRegister } from "@/components/pwa-register";
import { BootSplash } from "@/components/boot-splash";
import { TimezoneSync } from "@/components/timezone-sync";
import { getAccent, getTimeZone } from "@/lib/settings";

/* One family, two widths. Archivo is variable on width as well as weight, so
   the expanded cut that carries titles and numbers (a broadcast-scoreboard
   width) and the text face are a single file. Replaces a three-face stack
   (Archivo, IBM Plex Mono, Big Shoulders) and about 90 KB of font. */
const archivo = Archivo({
  variable: "--font-archivo",
  subsets: ["latin"],
  axes: ["wdth"],
  display: "swap",
});

export const metadata: Metadata = {
  title: {
    default: "Fatty: Strength Log",
    template: "%s · Fatty",
  },
  description:
    "Train like a Kengan fighter. Programs, savage-fast set logging, and power analytics that climb with every rep.",
  appleWebApp: {
    capable: true,
    title: "Fatty",
    statusBarStyle: "black-translucent",
    // iOS home-screen launch screens: a branded dark splash while the PWA
    // cold-starts, instead of a blank white flash. Generated by
    // scripts/generate-splash.mjs.
    startupImage: [
      { url: "/splash/splash-1290x2796.png", media: "screen and (device-width: 430px) and (device-height: 932px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)" },
      { url: "/splash/splash-1320x2868.png", media: "screen and (device-width: 440px) and (device-height: 956px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)" },
      { url: "/splash/splash-1206x2622.png", media: "screen and (device-width: 402px) and (device-height: 874px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)" },
      { url: "/splash/splash-1284x2778.png", media: "screen and (device-width: 428px) and (device-height: 926px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)" },
      { url: "/splash/splash-1179x2556.png", media: "screen and (device-width: 393px) and (device-height: 852px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)" },
      { url: "/splash/splash-1170x2532.png", media: "screen and (device-width: 390px) and (device-height: 844px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)" },
      { url: "/splash/splash-1125x2436.png", media: "screen and (device-width: 375px) and (device-height: 812px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)" },
      { url: "/splash/splash-1242x2688.png", media: "screen and (device-width: 414px) and (device-height: 896px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)" },
      { url: "/splash/splash-828x1792.png", media: "screen and (device-width: 414px) and (device-height: 896px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait)" },
      { url: "/splash/splash-750x1334.png", media: "screen and (device-width: 375px) and (device-height: 667px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait)" },
    ],
  },
};

export const viewport: Viewport = {
  themeColor: "#000000",
  width: "device-width",
  initialScale: 1,
  // No maximumScale: pinch-zoom stays available for accessibility; the 16px
  // input floor in globals.css already prevents iOS focus-zoom.
  viewportFit: "cover",
  // Shrink the viewport when the on-screen keyboard opens, so `100dvh` and
  // fixed-position chrome track the space actually left. Without this the
  // keyboard overlays the layout viewport and covers the bottom of a bottom
  // sheet, which is exactly where the set-logging inputs live.
  interactiveWidget: "resizes-content",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const [accent, timeZone] = await Promise.all([getAccent(), getTimeZone()]);
  return (
    <html
      lang="en"
      data-accent={accent}
      className={`${archivo.variable} h-full antialiased`}
    >
      <body className="min-h-full bg-bg text-text">
        <PwaRegister />
        <TimezoneSync serverTimeZone={timeZone} />
        {/* Installed-app boot sequence. Renders server-side so it paints on the
            first frame of a cold PWA start, then lifts itself once the app is
            up; a browser tab never sees it. */}
        <BootSplash />
        {children}
      </body>
    </html>
  );
}
