import type { Metadata, Viewport } from "next";
import { Archivo, IBM_Plex_Mono, Big_Shoulders } from "next/font/google";
import "./globals.css";
import { PwaRegister } from "@/components/pwa-register";
import { BootSplash } from "@/components/boot-splash";
import { getAccent } from "@/lib/settings";

/* ── The fight-card stack ──────────────────────────────────────────────────
   Three faces, all out of the signage-and-print lineage a fight promotion
   actually draws on, rather than the house faces every dark dashboard ships
   with. Body is Archivo (a grotesque cut for print/signage), data is IBM Plex
   Mono (warm, real tabular figures), and the display role is Big Shoulders —
   condensed Chicago-signage caps that read like an arena board. Big Shoulders
   is variable, so one family covers both the display and impact weights
   instead of loading a second face for the heavy end. */
const archivo = Archivo({
  variable: "--font-archivo",
  subsets: ["latin"],
});

const plexMono = IBM_Plex_Mono({
  variable: "--font-plex-mono",
  subsets: ["latin"],
  // 400 and 500 only. Plex Mono is not variable, so every extra cut is another
  // five subset files on the wire; nothing in the app renders mono above 500.
  weight: ["400", "500"],
});

const bigShoulders = Big_Shoulders({
  variable: "--font-big-shoulders",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Hell Blazer: Strength Log",
  description:
    "Train like a Kengan fighter. Programs, savage-fast set logging, and power analytics that climb with every rep.",
  appleWebApp: {
    capable: true,
    title: "Hell Blazer",
    statusBarStyle: "black-translucent",
    // iOS home-screen launch screens: a branded dark splash while the PWA
    // cold-starts, instead of a blank white flash. Generated by
    // scripts/generate-splash.mjs.
    startupImage: [
      { url: "/splash/splash-1290x2796.png", media: "screen and (device-width: 430px) and (device-height: 932px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)" },
      { url: "/splash/splash-1320x2868.png", media: "screen and (device-width: 440px) and (device-height: 956px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)" },
      { url: "/splash/splash-1206x2622.png", media: "screen and (device-width: 402px) and (device-height: 874px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)" },
      { url: "/splash/splash-1284x2778.png", media: "screen and (device-width: 428px) and (device-height: 926px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)" },
      { url: "/splash/splash-1179x2556.png", media: "screen and (device-width: 393px) and (device-height: 852px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)" },
      { url: "/splash/splash-1170x2532.png", media: "screen and (device-width: 390px) and (device-height: 844px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)" },
      { url: "/splash/splash-1125x2436.png", media: "screen and (device-width: 375px) and (device-height: 812px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)" },
      { url: "/splash/splash-1242x2688.png", media: "screen and (device-width: 414px) and (device-height: 896px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)" },
      { url: "/splash/splash-828x1792.png", media: "screen and (device-width: 414px) and (device-height: 896px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait)" },
      { url: "/splash/splash-750x1334.png", media: "screen and (device-width: 375px) and (device-height: 667px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait)" },
    ],
  },
};

export const viewport: Viewport = {
  themeColor: "#0a0908",
  width: "device-width",
  initialScale: 1,
  // No maximumScale: pinch-zoom stays available for accessibility; the 16px
  // input floor in globals.css already prevents iOS focus-zoom.
  viewportFit: "cover",
  // Shrink the viewport when the on-screen keyboard opens, so `100dvh` and
  // fixed-position chrome track the space actually left. Without this the
  // keyboard overlays the layout viewport and covers the bottom of a bottom
  // sheet, which is exactly where the set-logging inputs live.
  interactiveWidget: "resizes-content",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const accent = await getAccent();
  return (
    <html
      lang="en"
      data-accent={accent}
      className={`${archivo.variable} ${plexMono.variable} ${bigShoulders.variable} h-full antialiased`}
    >
      <body className="min-h-full bg-bg text-text">
        <PwaRegister />
        {/* Installed-app boot sequence. Renders server-side so it paints on the
            first frame of a cold PWA start, then lifts itself once the app is
            up; a browser tab never sees it. */}
        <BootSplash />
        {children}
      </body>
    </html>
  );
}
